#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely, shows "I am invincible!!!" on SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
