#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# where only the part of the name after the first dash is displayed

for file in *; do
    if [[ -e "$file" && ! "$file" =~ ^\. ]]; then
        if [[ "$file" == *-* ]]; then
            echo "${file#*-}"
        else
            echo "$file"
        fi
    fi
done
